### PR TITLE
Update ICON xmods

### PR DESCRIPTION
**Pull request by skosukhin**
1. Update git submodule reference to `omni-compiler`, which can handle the generation of `xmod` files of the following libraries almost without any additional patching.
2. Add `xmod` files for `YAXT 0.9.3.1`, which is currently used in `ICON`.
3. Update `xmod` files for `MTIME`:
    - move `xmod` files from the `1.0.8` subdirectory to `1.0.8-2b5fd81`, which is `1.0.8` with patches that had been used in `ICON` for a long time;
    - add `xmod` files for the actual version `1.0.8`;
    - add `xmod` files for version `1.0.11-rc2`, which is used in `ICON` currently.
4. Update `xmod` files for `CDI`:
   - add `xmod` files for version `1.8.3`, which had been used in `ICON` for a long time;
   - remove `xmod` files for version `1.8.x`, which are almost identical to `1.8.3` (all differences in the `xmod` files a caused by a [single additional line](https://gitlab.dkrz.de/mpim-sw/libcdi/-/blob/716d0dabe88185ebdbd8c059406da7faba073c14/src/mo_cdi.f90#L177) in the source code);
   - add `xmod` files for version `1.8.4`, which is used in `ICON` currently.
5. Add non-MPI and MPI versions of `xmod` files of `SCT 1.0-39390f0 ` library, which is currently used in `ICON`.
6. Add `xmod` files for `YAC`:
    - `2.4.2` - version that is used in `ICON` currently;
    - `2.5.4` - the latest version of the library.

Supersedes #19

### CODE REVIEW

**Comment by lxavier** [comment]
@skosukhin thanks a lot, I just see that the ci seems block  - I'll try to see if I can find out why (assume was not use for very long time)

**Comment by lxavier** [comment]
I will try to close and re-open to re-trigger travis after config changes

**Comment by lxavier** [comment]
ok - just checked. @skosukhin Travis is no longer free - only for very specific condidtion - so we'll have to move. If you know how to do it could you run the CLAW unittest manually and post the results here. After that I will merge. Since you are chaning the omni version we should make sure all test are ok

**Comment by skosukhin** [comment]
@lxavier please, take a look at #21. I will rebase this once that one is merged.

**Comment by skosukhin** [comment]
This [passes](https://github.com/skosukhin/omni-xmod-pool/runs/7668661370) the tests.

**Comment by lxavier** [comment]
thx !

**Comment by lxavier** [comment]
Note : the test was run with github action, see link in the comment. Overwrite merge protection to merge

**Pull request merged**
