### PR TITLE
Add yaxt xmods

### PR DESCRIPTION
**Pull request by skosukhin**
This PR adds xmods for [YAXT](https://gitlab.dkrz.de/dkrz-sw/yaxt) version 0.7.0 (currently used in ICON).

The script that was used for the generation:
```bash
#!/bin/bash

set -eu
set -o pipefail

yaxt_dir='/path/to/yaxt'
omni_xmod_pool_dir='/path/to/omni-xmod-pool'

output_dir="${omni_xmod_pool_dir}/yaxt/0.7.0"

FPP_FLAGS='-DHAVE_VOLATILE -DHAVE_FC_LOGICAL_INTEROP -DHAVE_FC_LOGICAL_C_BOOL -DHAVE_FC_PTR_BOUND_REMAP -DXT_MPI_AINT_KIND=c_long -DXT_MPI_FINT_FC_KIND=c_int -DXT_INT_FC_KIND=c_int -DXT_INT_FC_MPIDT=MPI_INTEGER4 -DSIZEOF_XT_INT=4'
OMNI_FLAGS="-M ${output_dir} -M ${omni_xmod_pool_dir}/mpi/3.0"

files='
xt_mpi_f.f90
xt_core_f.f90
xt_sort_f.f90
xt_idxlist_f.f90
xt_idxvec_f.f90
xt_idxstripes_f.f90
xt_idxsection_f.f90
xt_idxlist_collection_f.f90
xt_idxmod_f.f90
xt_xmap_f.f90
xt_xmap_intersection_f.f90
xt_request_f.f90
xt_redist_f.f90
xt_redist_int_i2.f90
xt_redist_int_i4.f90
xt_redist_int_i8.f90
xt_redist_logical.f90
xt_redist_real_sp.f90
xt_redist_real_dp.f90
yaxt.f90
'

mkdir -p "${output_dir}"
cd "${yaxt_dir}/src"

for f in ${files}; do
        gfortran -E -cpp ${FPP_FLAGS} $f | F_Front ${OMNI_FLAGS} >/dev/null
done
```

### CODE REVIEW

**Comment by skosukhin** [comment]
The checks fail on Travis (`The job exceeded the maximum log length, and has been terminated.`) but work on my workstation.

**Review by clementval — APPROVED** [review]
LGTM

Would it make sense to add your script somewhere in the repo so it is available if someone needs to redo it. 

Maybe in `/scripts/yaxt/`

**Comment by skosukhin** [comment]
@clementval done

**Review by clementval — APPROVED** [review]

**Comment by lxavier** [comment]
Since Micheal is away I could do the merge, but we need to find a way to get the CI working, I cannot merge otherwise
@skosukhin any idea ?

**Comment by skosukhin** [comment]
@lxavier it's green now

**Comment by lxavier** [comment]
@FrostyMike all green and reviewed by @clementval  so I merge myself, you can check it once you are back

**Pull request merged**
